### ISSUE TITLE
Deleting a song then immediately trying to play it loads you into a glitched level.

### ISSUE THREAD

**Issue by megalon** [andruzzzhka/BeatSaverDownloader#14]
Video example by ataraxy:
https://youtu.be/GPYMNnz04Ak

If you delete a song then click "play" on the same song right after deleting it you are loaded into a black level with the track data from $100 bills.

When the level ends you are stuck in the game and do not return to the menu.

You can open the in-game menu while the song is playing, but after it ends you cannot open the in-game menu.

**Comment by andruzzzhka** [comment]
Fixed
