### ISSUE TITLE
modprefs.ini file on Oculus

### ISSUE THREAD

**Issue by atrickpay** [andruzzzhka/BeatSaverDownloader#21]
I see the steam path in the instructions for "modprefs.ini" to add your token for voting, but I don't have the same folder structure for my Oculus games, and searching for a file of that name, or any .ini file, turns up nothing. If I need to make it, where should I put it? 

![beatsaber](https://user-images.githubusercontent.com/14261191/44382848-98ed7e00-a4e4-11e8-9fc9-3365d49e27d3.png)

**Comment by andruzzzhka** [comment]
It looks like for some reason the plugin didn't create the UserData folder.
Can you send your output_log.txt? ("%UserProfile%\AppData\LocalLow\Hyperbolic Magnetism\Beat Saber\output_log.txt")

**Comment by atrickpay** [comment]
That file pointed me in the right direction, I created a new Oculus install directory in C:\Games, and apparently there were some permission issues involved with doing that. Once I gave full control to my user and reloaded the game, the folder and modprefs.ini were created successfully, thank you very much! Great mod, appreciate the work & the help!
