### ISSUE TITLE
3.3.3 does not detect Songbrowser

### ISSUE THREAD

**Issue by Mace404** [andruzzzhka/BeatSaverDownloader#27]
Release 3.3.3 does not detect the Songbrowser and this results in double buttons in the song list.
![image](https://user-images.githubusercontent.com/41652357/57487028-c87d2a00-72af-11e9-9a53-e2b2215f26d1.png)

This log line is also missing (still present in 3.3.2):
[BeatSaverDownloader | LOG] Song Browser installed, disabling Song List Tweaks

I have Songbrowser.dll (3.0.6) installed.

**Comment by andruzzzhka** [comment]
Fixed!
