### ISSUE TITLE
No way to get access token (Oculus)

### ISSUE THREAD

**Issue by MikeGold** [andruzzzhka/BeatSaverDownloader#32]
API Token is not needed for Steam version, but I have BeatSaber from Oculus store and after registering on BeatSaver page there is no subpage to generate the token. Voting is grayed out for me.

**Comment by andruzzzhka** [comment]
As far as I know, there is no API access token on BeatSaver anymore

**Comment by MikeGold** [comment]
So if I'm on Oculus I'm out of luck?

**Comment by andruzzzhka** [comment]
Sounds like it, but you should ask Kyle1413 in BSMG Discord about this

**Comment by MikeGold** [comment]
"Oculus accounts currently cannot vote from in game as beatsaver does not currently support generating read/write api tokens and there is no way to vote via the api using an oculus id"
